@isTest(seeAllData=false)
public class sigmadummyClassTest1
{
   public static testMethod void sigmadummyClassTestMethod()
   {
     sigmadummyClass1 dc=new sigmadummyClass1();
     dc.dummyClassMethod1();
     dc.dummyClassMethod2();
     dc.dummyClassMethod3();
     dc.dummyClassMethod4();
     dc.dummyClassMethod5();
     dc.dummyClassMethod6();
     dc.dummyClassMethod7();
   }
    public static testMethod void dummyClassTestMethod2()
   {
     sigmaDummyClass2 dc=new sigmaDummyClass2();
     dc.dummyClassMethod1();
     dc.dummyClassMethod2();
     dc.dummyClassMethod3();
     dc.dummyClassMethod4();
     dc.dummyClassMethod5();
     dc.dummyClassMethod6();
     dc.dummyClassMethod7();
   }
   public static testMethod void dummyClassTestMethod4()
   {
     sigmaDummyClass4 dc=new sigmaDummyClass4();
     dc.dummyClassMethod1();
     dc.dummyClassMethod2();
     dc.dummyClassMethod3();
     dc.dummyClassMethod4();
     dc.dummyClassMethod5();
     dc.dummyClassMethod6();
     dc.dummyClassMethod7();
   }
   
   public static testMethod void dummyClassTestMethod5()
   {
     sigmaDummyClass5 dc=new sigmaDummyClass5();
     dc.dummyClassMethod1();
     dc.dummyClassMethod2();
     dc.dummyClassMethod3();
     dc.dummyClassMethod4();
     dc.dummyClassMethod5();
     dc.dummyClassMethod6();
     dc.dummyClassMethod7();
   }
   
}